import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";

export const metadata: Metadata = {
  title: "Predictify Pro.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" type="text/css" href="global.css"></link>
      </head>
      
      <body className="w-screen overflow-x-hidden" >

        <div className="sticky top-0 bottom-0 z-1" style={{zIndex:1}}>
          <Navbar />
        </div>
        <div style={{translate: '0px -95px'}}>
          <Hero />
        </div>

        <div className="h-[calc(100vh - 6rem)]">{children}</div>
      </body>
    </html>
  );
}
